spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parking
    username: postgres
    password: 1111

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      show_sql: true
      format_sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect